//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAPWebServisTesti.HesapMakinesiServis {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HesapMakinesiServis.HesapMakinesiSoap")]
    public interface HesapMakinesiSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        SOAPWebServisTesti.HesapMakinesiServis.HelloWorldResponse HelloWorld(SOAPWebServisTesti.HesapMakinesiServis.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAPWebServisTesti.HesapMakinesiServis.HelloWorldResponse> HelloWorldAsync(SOAPWebServisTesti.HesapMakinesiServis.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Toplama", ReplyAction="*")]
        int Toplama(int ilkSayi, int ikinciSayi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Toplama", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ToplamaAsync(int ilkSayi, int ikinciSayi);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public SOAPWebServisTesti.HesapMakinesiServis.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(SOAPWebServisTesti.HesapMakinesiServis.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public SOAPWebServisTesti.HesapMakinesiServis.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(SOAPWebServisTesti.HesapMakinesiServis.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HesapMakinesiSoapChannel : SOAPWebServisTesti.HesapMakinesiServis.HesapMakinesiSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HesapMakinesiSoapClient : System.ServiceModel.ClientBase<SOAPWebServisTesti.HesapMakinesiServis.HesapMakinesiSoap>, SOAPWebServisTesti.HesapMakinesiServis.HesapMakinesiSoap {
        
        public HesapMakinesiSoapClient() {
        }
        
        public HesapMakinesiSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HesapMakinesiSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HesapMakinesiSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HesapMakinesiSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOAPWebServisTesti.HesapMakinesiServis.HelloWorldResponse SOAPWebServisTesti.HesapMakinesiServis.HesapMakinesiSoap.HelloWorld(SOAPWebServisTesti.HesapMakinesiServis.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            SOAPWebServisTesti.HesapMakinesiServis.HelloWorldRequest inValue = new SOAPWebServisTesti.HesapMakinesiServis.HelloWorldRequest();
            inValue.Body = new SOAPWebServisTesti.HesapMakinesiServis.HelloWorldRequestBody();
            SOAPWebServisTesti.HesapMakinesiServis.HelloWorldResponse retVal = ((SOAPWebServisTesti.HesapMakinesiServis.HesapMakinesiSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAPWebServisTesti.HesapMakinesiServis.HelloWorldResponse> SOAPWebServisTesti.HesapMakinesiServis.HesapMakinesiSoap.HelloWorldAsync(SOAPWebServisTesti.HesapMakinesiServis.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOAPWebServisTesti.HesapMakinesiServis.HelloWorldResponse> HelloWorldAsync() {
            SOAPWebServisTesti.HesapMakinesiServis.HelloWorldRequest inValue = new SOAPWebServisTesti.HesapMakinesiServis.HelloWorldRequest();
            inValue.Body = new SOAPWebServisTesti.HesapMakinesiServis.HelloWorldRequestBody();
            return ((SOAPWebServisTesti.HesapMakinesiServis.HesapMakinesiSoap)(this)).HelloWorldAsync(inValue);
        }
        
        public int Toplama(int ilkSayi, int ikinciSayi) {
            return base.Channel.Toplama(ilkSayi, ikinciSayi);
        }
        
        public System.Threading.Tasks.Task<int> ToplamaAsync(int ilkSayi, int ikinciSayi) {
            return base.Channel.ToplamaAsync(ilkSayi, ikinciSayi);
        }
    }
}
